kind: Service
apiVersion: v1
metadata:
  name: spark-master-jh
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 4040
      targetPort: 4040
      name: spark-app
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: spark-master-jh
  type: ClusterIP